### ISSUE TITLE
plot_heatmap Error: cannot take a sample larger than the population when 'replace = FALSE'

### ISSUE THREAD

**Issue by bednarsky** [epigen/unsupervised_analysis#59]
Error:
> Attaching package: ‘fastcluster’
> 
> The following object is masked from ‘package:stats’:
> 
>     hclust
> 
> Error in sample.int(length(x), size, replace, prob) :
>   cannot take a sample larger than the population when 'replace = FALSE'
> Calls: sample -> sample.int

- I don't get more info than this, so not even sure which `sample` call causes the issue 
- input files seem fine
- potential clue: https://stackoverflow.com/questions/19648238/r-says-cannot-take-a-sample-larger-than-the-population-but-i-am-not-taking
- config settings:
  ```yaml
  heatmap:
      metrics: ['correlation','cosine']
      hclust_methods: ['complete']
      n_observations: 1 # random sampled proportion float (0-1] or absolute number as integer
      n_features: 0.5 # highly variable features proportion float (0-1] or absolute number as integer
  ```
